import { describe, it, expect } from "vitest";
import { generateCto } from "../src/cto-export.js";

describe("Concerto (.cto) exporter", () => {
  const cto = generateCto();

  it("emits a valid header with the atelier namespace", () => {
    expect(cto).toContain("namespace com.atelier@0.1.0");
    expect(cto).toContain("// Generated by @atelier/domain cto-export");
    expect(cto).toContain("Zod is the runtime authority");
  });

  it("groups declarations under Accord category headings", () => {
    expect(cto).toMatch(/──── participants/);
    expect(cto).toMatch(/──── assets/);
    expect(cto).toMatch(/──── concepts/);
    expect(cto).toMatch(/──── events/);
    expect(cto).toMatch(/──── transactions/);
  });

  it("maps person.principal to a participant declaration", () => {
    expect(cto).toMatch(/participant PersonPrincipal identified by id \{/);
    expect(cto).toContain("o String fullName");
    expect(cto).toContain("o String preferredName optional");
    expect(cto).toContain("o String[] emails");
  });

  it("maps place.property to an asset declaration", () => {
    expect(cto).toMatch(/asset PlaceProperty identified by id \{/);
    expect(cto).toContain("o String addressLine1");
    expect(cto).toContain("o String addressLine2 optional");
  });

  it("maps obligation.deadline to an event declaration and DateTime for dueAt", () => {
    expect(cto).toMatch(/event ObligationDeadline identified by id \{/);
    expect(cto).toContain("o DateTime dueAt");
  });

  it("maps action to a transaction declaration", () => {
    expect(cto).toMatch(/transaction Action identified by id \{/);
  });

  it("declares named enums for enum fields", () => {
    // person.member → relationToPrincipal enum
    expect(cto).toMatch(/enum PersonMemberRelationToPrincipal \{/);
    expect(cto).toContain("o SPOUSE");
    expect(cto).toContain("o CHILD");
    // obligation.deadline → category enum
    expect(cto).toMatch(/enum ObligationDeadlineCategory \{/);
    expect(cto).toContain("o RENEWAL");
    expect(cto).toContain("o SCHOOL");
  });

  it("flags unmapped shapes with a comment rather than dropping the field", () => {
    // preference.travel has z.record(z.unknown()) which the exporter
    // can't cleanly model; the field should still appear, annotated.
    expect(cto).toMatch(/o String value.*\/\/ unmapped:/);
  });

  it("maps vehicle year (int) to Integer", () => {
    // asset.vehicle → year: z.number().int().optional()
    expect(cto).toMatch(/o Integer year optional/);
  });

  it("every registered node type produces at least one identified-by declaration", () => {
    const matches = cto.match(/identified by id \{/g) ?? [];
    // 33 node types registered today. Assert we produced at least
    // that many decls (loose so this doesn't break on legit additions).
    expect(matches.length).toBeGreaterThanOrEqual(30);
  });
});
